export const USER_COURSE_GET_REQUEST = 'USER_COURSE_REQUEST';
export const USER_COURSE_GET_SUCCESS = 'USER_COURSE_SUCCESS';
export const USER_COURSE_GET_FAIL = 'USER_COURSE_FAIL';

export const USER_COURSE_POST_REQUEST = 'USER_COURSE_REQUEST';
export const USER_COURSE_POST_SUCCESS = 'USER_COURSE_SUCCESS';
export const USER_COURSE_POST_FAIL = 'USER_COURSE_FAIL';

export const USER_COURSE_STATUS_RESET = 'USER_COURSE_STATUS_RESET';